-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 14:13:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `techBook` DEFAULT CHARACTER SET utf8 ;
USE `techBook` ;

-- -----------------------------------------------------
-- Table `techBook`.`circle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techBook`.`circle` (
  `circle_url` VARCHAR(255) NOT NULL COMMENT 'サークル名',
  `circle` VARCHAR(255) NOT NULL COMMENT 'サークル名',
  `circle_image` VARCHAR(255) NOT NULL COMMENT 'サークルのイメージURL',
  `arr` VARCHAR(64) NOT NULL COMMENT '配置場所',
  `genere` VARCHAR(255) NOT NULL COMMENT 'ジャンル',
  `keyword` VARCHAR(255) NOT NULL COMMENT 'KeyWord',
  `title` VARCHAR(255) NOT NULL COMMENT '本の名前',
  `content` TEXT COMMENT '本の内容'
)
